### ISSUE TITLE
Bug - Seasonal timer keeps going even when the game is paused.

### ISSUE THREAD

**Issue by Lord-Kamina** [RustyMods/Seasonality#13]
Not much more to say other than the title. If season depends on the world's age, I don't know whether this can have further implications like seasons repeating or something like that, though.

**Comment by RustyMods** [comment]
this is by design

**Comment by Lord-Kamina** [comment]
Oh. Why, though?

**Comment by RustyMods** [comment]
using in-game time was finnicky and gave me a headache to make it work with the rest of my logic.
since in-game days are 30 minutes, whole system is based on seconds.
so i had to translate it to a visual timer that makes sense, 
was a headache that worked 80% of the time. so i was constantly answering peoples questions. 
so i decide to switch to real-time that way i didn't have to explain the game logic to people.
altho now im stuck explaining it again >>
